mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import *

app_name = "news"

urlpatterns = [
    #path('', index, name="index"),
    path('', HomeNews.as_view(), name="index"),
    #path('category/<int:category_id>/', get_category, name="category"),
    path('category/<int:category_id>/', NewsByCategory.as_view(), name="category"),
    #path('news/<int:news_id>/', view_news, name="view_news"),
    path('news/<int:pk>/', ViewNews.as_view(), name="view_news"),
    #path('news/add-news/', add_news, name="add_news"),
    path('news/add-news/', CreateNews.as_view(), name="add_news"),
    path('news/test/', test, name="test"),
    path('register/', register, name="register"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
]

news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        
    title = models.CharField(max_length=150,verbose_name='Наименование')
    content = models.TextField(blank=True,verbose_name='Содержание')
    created_ad = models.DateTimeField(auto_now_add=True,verbose_name='Дата создания')
    updated_ad = models.DateTimeField(auto_now=True,verbose_name='Дата изменения')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/',verbose_name='Фото',blank=True)
    is_published = models.BooleanField(default=True,verbose_name='Опубликован')
    category = models.ForeignKey('Category',on_delete=models.PROTECT,null=True,verbose_name='Категория')  
    views = models.IntegerField(default=0)
    
    def get_absolute_url(self):
        return reverse('view_news', kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.title
    
class Category(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    title = models.CharField(max_length=150,db_index=True,verbose_name='Наименование категории')
        
    def get_absolute_url(self):
        return reverse('category',kwargs={"category_id":self.pk})
        
    def __str__(self):
        return self.title

news/forms.py
from django import forms
from .models import News #Category
import re
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    subject = forms.CharField(label='Тема', widget=forms.TextInput(
    attrs={"class": "form-control"}))
    content = forms.CharField(label='Текст', required=False, widget=forms.Textarea(
    attrs={"class": "form-control", "rows" : 5}))

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(
    attrs={"class": "form-control"}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(
    attrs={"class": "form-control"}))

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя',help_text='Пароль должен состоять из 150 символов', widget=forms.TextInput(
    attrs={"class": "form-control"}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(
    attrs={"class": "form-control"}))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(
    attrs={"class": "form-control"}))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(
    attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        #fields = '__all__'
        fields = ['title','content','is_published','category']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
        }
        
    #def clean_title(self):
    #    title = self.cleaned_data['title']
    #    if re.match(r'\d',title):
    #        raise ValidationError('Название начинается с цифры')





    #title = forms.CharField(max_length=150, label='Название', widget=forms.TextInput(
    #attrs={"class": "form-control"}))
    #content = forms.CharField(label='Текст', required=False, widget=forms.Textarea(
    #attrs={"class": "form-control", "rows" : 5}))
    #is_published = forms.BooleanField(label='Опубликовано')
    #category = forms.ModelChoiceField(empty_label='Выберите категорию', queryset=Category.objects.all(),label='Категория', widget=forms.Select(
    #attrs={"class": "form-control"}))

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from .models import News, Category
from .forms import NewsForm, UserRegisterForm, UserLoginForm, ContactForm
from .utils import MyMixin
from django.contrib import messages
from django.contrib.auth import login, logout
from django.core.mail import send_mail


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегистировались.')
            return redirect('news:index')
        else:
            messages.error(request, 'Ошибка регистрации.')
    else:
        form = UserRegisterForm()
    aggr = {
        'form' : form,
    }
    return render(request, 'news/register.html', aggr)

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('news:index')
    else:
        form = UserLoginForm()
    aggr = {
        'form' : form,
    }
    return render(request, 'news/login.html', aggr)

def user_logout(request):
    logout(request)
    return redirect('news:login')

def test(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            mail = send_mail(form.cleaned_data['subject'], form.cleaned_data['content'], 'baimieff.volodya1@yandex.ru', ['baimieff.volodya@yandex.ru'], fail_silently=False)
            if mail:
                messages.success(request, 'Письмо отправлено.')
                return redirect('news:test')
            else:
                messages.error(request, 'Письмо не отправлено.')
    else:
        form = ContactForm()
    return render(request, 'news/test.html',{'form':form})
    # aggr = {
    #     'form' : form,
    # }
    # return render(request, 'news/register.html', aggr)

# def test(request):
#     objects = ['join1','join2','join3','join4',
#     'join5','join6','join7','join8','join9',
#     'join5','join6','join7','join8','join9',
#     'join5','join6','join7','join8','join9',
#     'join5','join6','join7','join8','join9',
#     'join5','join6','join7','join8','join9']

#     paginator = Paginator(objects, 2)
#     page_num = request.GET.get('page', 1)
#     page_obj = paginator.get_page(page_num)
#     return render(request, 'news/test.html',{'page_obj':page_obj})


class HomeNews(MyMixin, ListView):
    model = News #аналог news = News.objects.all()
    template_name = 'news/index.html'
    context_object_name = 'news'
    mixin_prop = 'Hello, world!!!'
    paginate_by = 2
    
    def get_queryset(self):
        return News.objects.filter(is_published=True).select_related('category')


#def index(request):
#    news = News.objects.all()
#    args = {
#        'news':news,
#    }
#    return render(request,'news/index.html',args)

class NewsByCategory(MyMixin, ListView):
    model = News
    template_name = 'news/category.html'
    context_object_name = 'news'
    allow_empty = False
    paginate_by = 2
    
    def get_queryset(self):
        return News.objects.filter(category_id=self.kwargs['category_id'], is_published=True).select_related('category')
    
#def get_category(request, category_id):
#    news = News.objects.filter(category_id=category_id)
    # category = Category.objects.get(pk=category_id)
#    category = get_object_or_404(Category, pk=category_id)
#    args = {
#        'news':news,
#        'category': category,
#    }
#    return render(request,'news/category.html',args)

class ViewNews(DetailView):
    model = News
    # pk_url_kwarg = 'news_id'
    template_name = 'news/view_news.html'
    context_object_name = 'news_item'
    
    
#def view_news(request, news_id):
    # news_item = News.objects.get(pk=news_id)
#    news_item = get_object_or_404(News, pk=news_id)
#    args = {
#        'news_item': news_item,
#    }
#    return render(request,'news/view_news.html', args)

class CreateNews(LoginRequiredMixin, CreateView):
    form_class = NewsForm
    template_name = 'news/add_news.html'
    success_url = reverse_lazy('news:index')
    login_url = reverse_lazy('news:index')
    
    
    
#def add_news(request):
#    if request.method == 'POST':
#        form = NewsForm(request.POST)
#        if form.is_valid():
#            form.save()
#            return redirect('news:index')
#    else:
#        form = NewsForm()
#    args = {
#        'form' : form,
#    }
#    return render(request, 'news/add_news.html', args)

news/templates/news/add_news.html
{% extends 'base.html' %}

{% block title %}
	Добавление новости 
{% endblock %}

	
{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
	<h1>Добавление новости</h1>
	<form method="POST">
		{% csrf_token %}
		
		{% comment %}
		{% for field in form %}
			<div class="form-group">
				{{ field.label_tag }}
				{{ field }}
				<div class="invalid-feedback">
					{{ field.errors }}
				</div>
			</div>
		{% endfor %}
		{% endcomment %}
			
		{% comment %}
		{{ form.non_field.errors }}
		<div class="form-group">
			<label for="{{ form.title.id_for_lable }}">Название: </label>
			{{ form.title }}
			<div class="invalid-feedback">
				{{ form.title.errors }}
			</div>
		</div>
		
		<div class="form-group">
			<label for="{{ form.content.id_for_lable }}">Текст: </label>
			{{ form.content }}
			<div class="invalid-feedback">
				{{ form.content.errors }}
			</div>
		</div>
		
		<div class="form-group">
			<label for="{{ form.is_published.id_for_lable }}">Опубликовано: </label>
			{{ form.is_published }}
			<div class="invalid-feedback">
				{{ form.is_published.errors }}
			</div>
		</div>
		
		<div class="form-group">
			<label for="{{ form.category.id_for_lable }}">Категория: </label>
			{{ form.category }}
			<div class="invalid-feedback">
				{{ form.category.errors }}
			</div>
		</div>
		{% endcomment %}
		
		{{ form.as_p }}
		
		<button type="submit" class="btn btn-primary btn-block">Добавить новость</button>
	</form>
{% endblock %}

news/templates/news/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>
			{% block title %}
				News
			{% endblock %}
		</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	</head>
	<body>
		{% block menu %}
		{% endblock %}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
	</body>
</html>

news/templates/news/category.html
{% extends 'base.html' %}

{% block title %}
	{{ category.title }}
{% endblock %}

{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}
	
{% block content %}
	{% for item in news %}
		<div class="card mb-3">
			<div class="card-header">
				Категория: <a href="{% url 'news:category' item.category.pk %}">{{ item.category }}</a>
			</div>
			<div class="card-body">
				<div class="media">
					{% if item.photo %}
						<img src="{{ item.photo.url }}" alt="">
					{% endif %}
					<div class="media-body">
						<h5 class="card-title">{{ item.title }}</h5>
						<p class="card-text">{{ item.content|linebreaks|truncatewords:50 }}</p>
						<a href="{% url 'news:view_news' item.pk %}" class="btn btn-primary">Read more...</a>
					</div>
				</div>
			</div>
			<div class="card-footer text-muted">
				{{ item.created_ad|date:"Y-m-d H:i:s" }}
			</div>
		</div>
		{% endfor %}
{% endblock %}

news/templates/news/index.html
{% extends 'base.html' %}

{% block title %}
	News 
{% endblock %}

	
{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
	{% for item in news %}
		<div class="card mb-3">
			<div class="card-header">
				Категория: <a href="{% url 'news:category' item.category.pk %}">{{ item.category }}</a>
			</div>
			<div class="card-body">
				<div class="media">
					{% if item.photo %}
						<img src="{{ item.photo.url }}" alt="">
					{% endif %}
					<div class="media-body">
						<h5 class="card-title">{{ item.title }}</h5>
						<p class="card-text">{{ item.content|safe|linebreaks|truncatewords:50 }}</p>
						<a href="{% url 'news:view_news' item.pk %}" class="btn btn-primary">Read more...</a>
					</div>
				</div>
			</div>
			<div class="card-footer text-muted">
				{{ item.created_ad|date:"Y-m-d H:i:s" }}
			</div>
		</div>
	{% endfor %}
{% endblock %}

news/templates/news/login.html
{% extends 'base.html' %}

{% block title %}
	Авторизация 
{% endblock %}

	
{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
	<h1>Авторизация</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary btn-block">Авторизоваться</button>
	</form>
{% endblock %}

news/templates/news/register.html
{% extends 'base.html' %}

{% block title %}
	Регистрация 
{% endblock %}

	
{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
	<h1>Регистрация</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary btn-block">Регистрация</button>
	</form>
{% endblock %}

news/templates/news/test.html
{% extends 'base.html' %}

{% block title %}
    Обратная связь
{% endblock %}

    
{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

    <h1>Обратная связь</h1>
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<button type='submit' class='btn btn-primary btn-block'>Отправить письмо</button>
    </form>
        
{% endblock %}

news/templates/news/view_news.html
{% extends 'base.html' %}

{% block title %}
	{{ news_item.title }}
{% endblock %}

	
{% block sidebar %}
	{% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
	<div class="card mb-3">
		<div class="card-header">
			Категория: <a href="{% url 'news:category' news_item.category.pk %}">{{ news_item.category }}</a>
		</div>
		<div class="card-body">
			{% if news_item.photo %}
				<img src="{{ news_item.photo.url }}" alt="" class="float-left mr-3">
			{% endif %}
			<h5 class="card-title">{{ news_item.title }}</h5>
			<p class="card-text">{{ news_item.content|safe|linebreaks }}</p>
		</div>
		<div class="card-footer text-muted">
			{{ news_item.created_ad|date:"Y-m-d H:i:s" }}
		</div>
	</div>
{% endblock %}