mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import *

app_name = "news"

urlpatterns = [
    #path('', index, name="index"),
    path('', HomeNews.as_view(), name="index"),
    #path('category/<int:category_id>/', get_category, name="category"),
    path('category/<int:category_id>/', NewsByCategory.as_view(), name="category"),
    #path('news/<int:news_id>/', view_news, name="view_news"),
    path('news/<int:pk>/', ViewNews.as_view(), name="view_news"),
    #path('news/add-news/', add_news, name="add_news"),
    path('news/add-news/', CreateNews.as_view(), name="add_news"),
    path('news/test/', test, name="test"),
    path('register/', register, name="register"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
]

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'news:index' %}">Navbar</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item"><a class="nav-link" href="{% url 'news:index' %}">Главная</a></li>
			{% if request.user.is_authenticated %}
			<li class="nav-item"><a class="nav-link" href="{% url 'news:add_news' %}">Добавить новость</a></li>
			{% endif %}
		</ul>
		<span class="navbar-text">
			{% if request.user.is_authenticated %}
	      		Добро пожаловать, {{ user.username }} | 
	      		<a href="{% url 'news:logout' %}">Выход</a>
	      	{% else %}
	      	<a href="{% url 'news:register' %}">Регистрация</a> | 
	      	<a href="{% url 'news:login' %}">Авторазация</a>
	      	{% endif %}
	    </span>
	</div>
</nav>

templates/inc/_sidebar.html
{% load news_tags %}
<div class="list-group">
	{% get_categories as categories %}
	{% for item in categories %}
		<a href="/category/{{ item.pk }}" class="list-group-item list-group-item-action">{{ item.title }}</a>
	{% endfor %}
</div>